<a href="https://colab.research.google.com/github/Kavish1504/Cognitivie-Computing-Assignments/blob/main/Cognitive_Computing__Assignment_4(102317012).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name-Kavish Gupta**

**Roll No.-102317012**

**Subgroup-2Q11**

**Assignment-4**

In [ ]:
import numpy as np
c=np.array([1,2,3,4,5])
for i in range(0,5):
    c[i]=c[i]+2
for i in range(0,5):
    print(c[i])

3
4
5
6
7


In [ ]:
import numpy as np
c=np.array([1,2,3,4,5])
for i in range(0,5):
    c[i]=c[i]*3
for i in range(0,5):
    print(c[i])

3
6
9
12
15


In [ ]:
import numpy as np
c=np.array([2,4,6,8,10])
for i in range(0,5):
    c[i]=c[i]/2
for i in range(0,5):
    print(c[i])

1
2
3
4
5


In [ ]:
import numpy as np
c=np.array([1,2,3,4,5])
i=0
j=4
while(i<=j):
    temp=c[i]
    c[i]=c[j]
    c[j]=temp
    i=i+1
    j=j-1

for i in range(0,5):
    print(c[i],end=' ')

5 4 3 2 1 

In [ ]:
import numpy as np
c=np.array([1,2,3,4,5,1,2,1,1,1])
l=[]
# list1=list(c)
# print(list1)
for i in range(1,6):
    size=c.size
    j=0
    count=0
    while(j<=size-1):
        if(c[j]==i):
            count=count+1
        j=j+1
    l.append(count)
maxi=max(l)
element=l.index(maxi)+1
print(f"Maximum element is {element} and its count in array is {maxi}")
size=c.size
i=0
while(i<size):
    if(c[i]==element):
        print(i,end=' ')
    i=i+1




Maximum element is 1 and its count in array is 5
0 5 7 8 9 

In [ ]:
import numpy as np
c=np.array([1,1,1,2,3,4,2,2,3,3])
l=[]
# list1=list(c)
# print(list1)
for i in range(1,6):
    size=c.size
    j=0
    count=0
    while(j<=size-1):
        if(c[j]==i):
            count=count+1
        j=j+1
    l.append(count)
maxi=max(l)
element=l.index(maxi)+1
print(f"Maximum element is {element} and its count in array is {maxi}")
size=c.size
i=0
while(i<size):
    if(c[i]==element):
        print(i,end=' ')
    i=i+1

Maximum element is 1 and its count in array is 3
0 1 2 

In [ ]:
import numpy as np
matrix=np.array([[10,20,30,100],[40,50,60,2000],[70,80,90,3000]])
size=matrix.shape[0]
print(matrix[0])
i=0
for i in range(0,size):
    print(matrix[i][1],end=' ')
print("\n")
print(matrix[2])
for i in range(0,size):
    print(matrix[i][0],end=' ')

[ 10  20  30 100]
20 50 80 

[  70   80   90 3000]
10 40 70 

In [ ]:
import numpy as np
import random
l=[]
# for i in range(1,26):
#     r=random.randint(10,100)
#     l.append(r)
Kavish=np.linspace(10,100,25)
print(Kavish)
print(Kavish.ndim)
sh=Kavish.shape
print(sh)
size=Kavish.size
print(size)
print(Kavish.nbytes)
print(Kavish.dtype)
print(Kavish.reshape(5,5))

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
200
float64
[[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]


In [ ]:
import numpy as np
ucs420_Kavish=np.array([[10,20,30],[40,50,60],[70,80,90],[15,20,35]])
print(ucs420_Kavish.sum()/12)
l=[]
for i in range(ucs420_Kavish.shape[0]):
    for j in range(ucs420_Kavish.shape[1]):
        l.append(ucs420_Kavish[i][j])
print(l)
l.sort
size=len(l)
print(size)
if(size%2!=0):
    print(l[int(size/2)])
else:
    index=int(size/2)
    print((l[index] + l[index+1])/2)
print(max(l))
print(min(l))
count=0
for i in range(0,size-1):
    if(l[i]!=l[i+1]):
        count=count+1
print(count)
print(ucs420_Kavish.reshape(4,3))
reshaped_ucs420_Kavish=ucs420_Kavish.reshape(4,3)
print(reshaped_ucs420_Kavish.reshape(2,3))

43.333333333333336
[10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35]
12
75.0
90
10
11
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


ValueError: cannot reshape array of size 12 into shape (2,3)